$(document).ready(function(){
    $("#signup-form").validate({
        rules:{
            fname:{
                required:true,
                minlength:4
            },
            sname:{
                required:true,
                minlenth:6
                },
            email:{
                required:true,
                email:true
            },
            password:{
                required:true,
                minlength:6
            },
        }
        
    })
})